### ISSUE TITLE
Can be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by sternschnaube** [jjblock21/ContainerSearch#4]
Tested on Fabric.

**Comment by jjblock21** [comment]
It worked for me on 1.20.2 before, but when I tested it yesterday it was broken, so I will release a fix for 1.20.2 with everything properly updated.

**Comment by jjblock21** [comment]
Update is released

**Comment by jjblock21** [comment]
May still need to be approved

**Comment by sternschnaube** [comment]
Thanks for letting me know ☺️
